### ISSUE TITLE
Strange Behavior of Global Planner

### ISSUE THREAD

**Issue by repa1030** [hatem-darweesh/core_planning#8]
Hello,

I am using OpenPlanner with Carla and Autoware VectorMaps (Branch 1.15) and I recognized strange behavior of the global planner in some situations (especially in lane change). Most times, it works just fine but at some points of the maps, it produces paths that do not follow any lane (see picture below). Is this related to the Vector Map or an issue of Global Planner?

In this case, the vector maps look a little bit corrupted so maybe that is causing the strange behavior here:
![Screenshot from 2021-07-02 11-58-12](https://user-images.githubusercontent.com/54360863/128320814-20c2b627-2051-474d-a976-5ce3479ca5c2.png)

But the global planner also have problems with this intersection (cutting corner) but the vector map here seems fine:
![Screenshot from 2021-08-05 10-49-50](https://user-images.githubusercontent.com/54360863/128321538-7bdbfe22-76e6-4924-ac92-c830e7bcf39a.png)

Thanks for your help!

**Comment by hatem-darweesh** [comment]
Sorry for late reply, 
OpenDRIVE conversion has some issues. specially if you will use lane change. connecting parallel lanes are not perfect because it is achieved automatically. 
to guarantee this to work, review the converted map manually to make sure all the connections between lanes are correct.
